# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "public_network", ip: "192.168.2.10"

  config.vm.provision "shell", path: "bootstrap.sh"

   config.vm.provider :virtualbox do |vb|
    # enable promiscuous mode on the public network
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
  end
end
